### ISSUE TITLE
support play 2.4

### ISSUE THREAD

**Issue by keepscoding** [manuelbernhardt/reactive-web-applications#1]
do u plan to change all the codes into 2.4 before final release?

**Comment by lucianenache** [comment]
I would second on that, there are some incompatibility and function name changing issues inside the code in order to be 2.4 compatible.

**Comment by keepscoding** [comment]
It will good to it will come with 2.4 especially working on DI part.

**Comment by sergeda** [comment]
One more for that

**Comment by keepscoding** [comment]
book will be outdated once release if not keeps in the pace with play development.

**Comment by keepscoding** [comment]
i think most people want to get into DI especially migration
If the book come with DI, it will be first and only(i think) book. maybe become a hot cake?

**Comment by manuelbernhardt** [comment]
The book is now upgraded to 2.4. Note that I won't be able to upgrade to 2.5 because the book will go to print earlier than the 2.5 release (not to mention all the libraries I'd have to wait for in order to be able to upgrade to 2.5). But it shouldn't matter that much, the concepts remain the same

**Comment by keepscoding** [comment]
it is the problem of play. You just have to keep playing to keep up the change...
