### ISSUE TITLE
Ch10 pt 10.1.2 Add selenium-firefox-driver to build.sbt

### ISSUE THREAD

**Issue by murmelsson** [manuelbernhardt/reactive-web-applications#14]
To get the test to run, I needed to add the following dependency into `build.sbt `

`"org.seleniumhq.selenium" % "selenium-firefox-driver" % "2.53.0"`

without this line, or with an outdated firefox-driver-specification e.g 2.46.0, selenium complains that:
Was unable to create a Selenium FirefoxDriver on this platform. (OneBrowserPerSuite.scala:333)

(It seems that Selenium drivers are quite picky about which browser-versions they are compatible with. So for example on Ubuntu, with Firefox 45.0.1, using the latest selenium-driver-version (as recommended - currently 2.53.0 as of 14.04.2016) is the solution here. With browsers like Firefox having a quick release cycle, and users generally accepting the updates, then the 2.53.0 will at some point cause brokenness, and so on).

So anyway the libraryDependencies I used in build.sbt to get the test to work are now defined as:
```
libraryDependencies ++= Seq(
  "org.webjars" %% "webjars-play" % "2.4.0-1",
  "org.webjars" % "jquery" % "2.1.4",
  "org.seleniumhq.selenium" % "selenium-firefox-driver" % "2.53.0",
  "org.scalatest" %% "scalatest" % "2.2.1" % "test",
  "org.scalatestplus" %% "play" % "1.4.0-M4" % "test"
)
```

Can put this as a PR (if you prefer).

--
Anyway and slightly off-topic, really an excellent book, this "Reactive Web Applications", been learning a lot going through the MEAP-version chapters - thanks Manuel!

**Comment by manuelbernhardt** [comment]
Thanks! I integrated this in the code and the book.
