### ISSUE TITLE
Will this book update Akka version to 2.4?

### ISSUE THREAD

**Issue by xring** [manuelbernhardt/reactive-web-applications#15]
It seems Akka version in codes on Github is still 2.3.x, will you rewrite some contents of the book and update Akka version to 2.4?

**Comment by manuelbernhardt** [comment]
The book uses 2.4 whenever possible (see e.g. https://github.com/manuelbernhardt/reactive-web-applications/blob/master/CH06/build.sbt). 2.3 is used for chapter 7 in which there's a dependency on the `akka-persistence-mongo-casbah` library which supported only 2.3 at the time of writing. That is, to the best of my knowledge, the API of akka-persistence does not differ much between 2.3 and 2.4.
